# Generated by Django 5.0.3 on 2024-03-23 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_message_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
