# Generated by Django 5.0.3 on 2024-03-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0003_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt', models.TextField(max_length=300)),
                ('name', models.CharField(default='Anonymous', max_length=50)),
                ('is_read', models.BooleanField()),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='')),
            ],
        ),
    ]
