# Generated by Django 5.0.3 on 2024-03-23 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_cnt_message_message_message_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='to',
        ),
    ]
