# Generated by Django 5.0.3 on 2024-04-01 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_message_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='name',
            new_name='nickname',
        ),
    ]
